### PR TITLE
Dts bugfix #267

### LINKED ISSUE #267: d.ts for 'x'
@richytong im noticed: no d.ts in 'x' directory.
im in progress fix it

### PR DESCRIPTION
**Pull request by kalagin**
closes #267 #185

1. generate d.ts for `x`
2. add dts command before `./build`
3. convert monad/Instance.js to class, fix this problem:
```sh
➜  rubico git:(dts-bugfix) ✗ nr dts

> rubico@2.3.0 dts
> del *.d.ts _internal/*.d.ts x/*.d.ts && tsc

monad/Instance.js:7:1 - error TS9005: Declaration emit for this file requires using private name 'Instance'. An explicit type annotation may unblock declaration emit.

7 'use strict'
  ~~~~~~~~~~~~


Found 1 error in monad/Instance.js:7
```

### CODE REVIEW

**Comment by kalagin** [comment]
@richytong please check monad/Instance.js - convert from function style class to es6 class is legal?

**Comment by richytong** [comment]
@kalagin yes that should be fine

**Comment by richytong** [comment]
I've refactored instance to use es6 class @kalagin. The changes are on master branch.

**Comment by kalagin** [comment]
@richytong done

**Comment by richytong** [comment]
@kalagin the files should be fixed already, I should have included the ts files

**Comment by kalagin** [comment]
ready to prod

**Review by richytong — APPROVED** [review]
LGTM

**Pull request merged**
