### PR TITLE
Draft: testing d.ts

### PR DESCRIPTION
**Pull request by kalagin**
#185 

@richytong hi!

Its only for demo. We can create d.ts for each exported function (https://rubico.land/docs) for the first time. In some types you don't have to bother with generic - the main idea is to give access to users with ts. 
We can write d.ts and copy to dist

what you think about it?

### CODE REVIEW

**Comment by richytong** [comment]
Hello @kalagin I'm not too familiar with TypeScript. Can we move the d.ts files to their own directory?

**Comment by kalagin** [comment]
@richytong yes, we can create 1 d.ts file, for e.g index.d.ts and specify in package.json

```json
....
  "types": "index.d.ts",
....
```

**Comment by richytong** [comment]
@kalagin I am good with all the types living in the index.d.ts file. Do you have a plan for adding the rest of the types?

**Comment by richytong** [comment]
@kalagin let's move the types in this pr to the index.d.ts file

**Comment by kalagin** [comment]
@richytong im create tsc command for generating:

```
npm run types
```

it generates index.d.ts. it works
but i have problem (see demo.ts)

```ts
// in this case works fine
const areNamesEqual = eq("Ted", "George");
console.log(areNamesEqual); // false

// but in this case we need cast types
const personIsGeorge = eq((person: Person) => person.name, "George") as (person: any) => boolean;
```

we need cast types, because tsc generate type for `eq` like this:

```ts
function eq(left: any, right: any): boolean | ((value: any) => any);
```
without generics and overloads.

i think we can generate once and fix generated types and write generics like in eq.d.ts (prev commit)

while thinking what to do

**Comment by kalagin** [comment]
next idea: we can overwrite union types like `boolean | ((value: any) => any)` to `any`, user will can use library with typescript. and then i can write types step-by-step with tests/type-tests

**Comment by richytong** [comment]
I think it's a good direction @kalagin . I would opt to keep the types as simple as possible, so use any when possible. I had a feeling it would be this challenging to do the types.

**Comment by kalagin** [comment]
@richytong i cant make one d.ts, because with this solution tree-shaking not working `import eq from 'rubico/eq`

we can generate d.ts for each file into dist, but dist should become "root" folders for imports. 
what do you think?
whats purpose of dist folder?

**Comment by richytong** [comment]
@kalagin I think it's probably the best to go your original proposal of having a d.ts file for each exported function. Do you know if we have to make a d.ts file for a module export like `index.js`?

Also the `dist` folder is for browser exports using unpkg as a cdn. The imports look like this
```
<script src="https://unpkg.com/rubico/dist/global.min.js"></script>
```

**Comment by kalagin** [comment]
@richytong im add d.ts for each js file (`npm run dts`)
in the future we can get file by file, write advanced types and add ready d.ts files to exclude in tsconfig.json

**Review by richytong — COMMENTED** [review]
Thank you @kalagin this is an enormous amount of work. This looks good to me as is.

**Review by richytong — APPROVED** [review]

**Comment by richytong** [comment]
I'm going to merge the changes now. Feel free to open another issue or PR if there is anything else.

**Pull request merged**
